### ISSUE TITLE
SavePosition not working

### ISSUE THREAD

**Issue by Rochet2** [Rochet2/AIO#10]
AIO.SavePosition is not working at all and probably never has.
The library the saving is using is being used completely wrong.

Should look into the docs of https://www.wowace.com/projects/libwindow-1-1 and figure out how it actually works, then correct the docs and implementation of AIO to reflect actual use.

**Comment by yuanf225** [comment]
Can AIO be modified to support Oregoncore

**Comment by Rochet2** [comment]
> Can AIO be modified to support Oregoncore

You are free to do so. I have no time to do any conversion efforts at the moment.

**Comment by yuanf225** [comment]
Hasn't this BUG been fixed yet?

**Comment by Rochet2** [comment]
Nope.

**Comment by Rochet2** [comment]
Hmm. Not sure what the original issue was. In any case, the code seems to be working fine.
The frame needs to have a name though, but trying to use a frame without a name will print an error message already.
