### ISSUE TITLE
AIo log errors 

### ISSUE THREAD

**Issue by Thordekk** [Rochet2/AIO#15]
lua_scripts/AIO_Server/Dep_crc32lua/crc32lua.lua:144: module 'bit' not found:
	
	no precompiled script '{}' found
	no field package.preload['bit']
	no file 'lua_scripts/bit.lua'
	no file 'lua_scripts/bit.ext'
	no file 'lua_scripts/bit.moon'
	no file 'lua_scripts/AIO_Server/bit.lua'
	no file 'lua_scripts/AIO_Server/bit.ext'
	no file 'lua_scripts/AIO_Server/bit.moon'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.lua'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.ext'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.moon'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.lua'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.ext'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.moon'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.lua'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.ext'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.moon'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.lua'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.ext'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.moon'
	no file 'lua_scripts/extensions/bit.lua'
	no file 'lua_scripts/extensions/bit.ext'
	no file 'lua_scripts/extensions/bit.moon'
	no file 'lua_scripts/extensions/StackTracePlus/bit.lua'
	no file 'lua_scripts/extensions/StackTracePlus/bit.ext'
	no file 'lua_scripts/extensions/StackTracePlus/bit.moon'
	no file 'lua_scripts/bit.dll'
	no file 'lua_scripts/bit.so'
	no file 'lua_scripts/AIO_Server/bit.dll'
	no file 'lua_scripts/AIO_Server/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.so'
	no file 'lua_scripts/extensions/bit.dll'
	no file 'lua_scripts/extensions/bit.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit.so'
module 'bit32' not found:
	
	no precompiled script '{}' found
	no field package.preload['bit32']
	no file 'lua_scripts/bit32.lua'
	no file 'lua_scripts/bit32.ext'
	no file 'lua_scripts/bit32.moon'
	no file 'lua_scripts/AIO_Server/bit32.lua'
	no file 'lua_scripts/AIO_Server/bit32.ext'
	no file 'lua_scripts/AIO_Server/bit32.moon'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.lua'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.ext'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.moon'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.lua'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.ext'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.moon'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.lua'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.ext'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.moon'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.lua'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.ext'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.moon'
	no file 'lua_scripts/extensions/bit32.lua'
	no file 'lua_scripts/extensions/bit32.ext'
	no file 'lua_scripts/extensions/bit32.moon'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.lua'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.ext'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.moon'
	no file 'lua_scripts/bit32.dll'
	no file 'lua_scripts/bit32.so'
	no file 'lua_scripts/AIO_Server/bit32.dll'
	no file 'lua_scripts/AIO_Server/bit32.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.so'
	no file 'lua_scripts/extensions/bit32.dll'
	no file 'lua_scripts/extensions/bit32.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.so'
module 'bit.numberlua' not found:
	
	no precompiled script '{}' found
	no field package.preload['bit.numberlua']
	no file 'lua_scripts/bit\numberlua.lua'
	no file 'lua_scripts/bit\numberlua.ext'
	no file 'lua_scripts/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.moon'
	no file 'lua_scripts/extensions/bit\numberlua.lua'
	no file 'lua_scripts/extensions/bit\numberlua.ext'
	no file 'lua_scripts/extensions/bit\numberlua.moon'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.lua'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.ext'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.moon'
	no file 'lua_scripts/bit\numberlua.dll'
	no file 'lua_scripts/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.so'
	no file 'lua_scripts/extensions/bit\numberlua.dll'
	no file 'lua_scripts/extensions/bit\numberlua.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.so'
	no file 'lua_scripts/bit.dll'
	no file 'lua_scripts/bit.so'
	no file 'lua_scripts/AIO_Server/bit.dll'
	no file 'lua_scripts/AIO_Server/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.so'
	no file 'lua_scripts/extensions/bit.dll'
	no file 'lua_scripts/extensions/bit.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit.so'
module 'bit53' not found:
	
	no precompiled script '{}' found
	no field package.preload['bit53']
	no file 'lua_scripts/bit53.lua'
	no file 'lua_scripts/bit53.ext'
	no file 'lua_scripts/bit53.moon'
	no file 'lua_scripts/AIO_Server/bit53.lua'
	no file 'lua_scripts/AIO_Server/bit53.ext'
	no file 'lua_scripts/AIO_Server/bit53.moon'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.lua'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.ext'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.moon'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.lua'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.ext'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.moon'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.lua'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.ext'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.moon'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.lua'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.ext'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.moon'
	no file 'lua_scripts/extensions/bit53.lua'
	no file 'lua_scripts/extensions/bit53.ext'
	no file 'lua_scripts/extensions/bit53.moon'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.lua'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.ext'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.moon'
	no file 'lua_scripts/bit53.dll'
	no file 'lua_scripts/bit53.so'
	no file 'lua_scripts/AIO_Server/bit53.dll'
	no file 'lua_scripts/AIO_Server/bit53.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.so'
	no file 'lua_scripts/extensions/bit53.dll'
	no file 'lua_scripts/extensions/bit53.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.so'
lua_scripts/AIO_Server/Dep_crc32lua/crc32lua.lua:144: module 'bit' not found:
	
	no precompiled script '{}' found
	no field package.preload['bit']
	no file 'lua_scripts/bit.lua'
	no file 'lua_scripts/bit.ext'
	no file 'lua_scripts/bit.moon'
	no file 'lua_scripts/AIO_Server/bit.lua'
	no file 'lua_scripts/AIO_Server/bit.ext'
	no file 'lua_scripts/AIO_Server/bit.moon'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.lua'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.ext'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.moon'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.lua'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.ext'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.moon'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.lua'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.ext'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.moon'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.lua'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.ext'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.moon'
	no file 'lua_scripts/extensions/bit.lua'
	no file 'lua_scripts/extensions/bit.ext'
	no file 'lua_scripts/extensions/bit.moon'
	no file 'lua_scripts/extensions/StackTracePlus/bit.lua'
	no file 'lua_scripts/extensions/StackTracePlus/bit.ext'
	no file 'lua_scripts/extensions/StackTracePlus/bit.moon'
	no file 'lua_scripts/bit.dll'
	no file 'lua_scripts/bit.so'
	no file 'lua_scripts/AIO_Server/bit.dll'
	no file 'lua_scripts/AIO_Server/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.so'
	no file 'lua_scripts/extensions/bit.dll'
	no file 'lua_scripts/extensions/bit.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit.so'
module 'bit32' not found:
	
	no precompiled script '{}' found
	no field package.preload['bit32']
	no file 'lua_scripts/bit32.lua'
	no file 'lua_scripts/bit32.ext'
	no file 'lua_scripts/bit32.moon'
	no file 'lua_scripts/AIO_Server/bit32.lua'
	no file 'lua_scripts/AIO_Server/bit32.ext'
	no file 'lua_scripts/AIO_Server/bit32.moon'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.lua'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.ext'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.moon'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.lua'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.ext'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.moon'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.lua'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.ext'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.moon'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.lua'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.ext'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.moon'
	no file 'lua_scripts/extensions/bit32.lua'
	no file 'lua_scripts/extensions/bit32.ext'
	no file 'lua_scripts/extensions/bit32.moon'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.lua'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.ext'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.moon'
	no file 'lua_scripts/bit32.dll'
	no file 'lua_scripts/bit32.so'
	no file 'lua_scripts/AIO_Server/bit32.dll'
	no file 'lua_scripts/AIO_Server/bit32.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit32.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit32.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit32.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit32.so'
	no file 'lua_scripts/extensions/bit32.dll'
	no file 'lua_scripts/extensions/bit32.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit32.so'
module 'bit.numberlua' not found:
	
	no precompiled script '{}' found
	no field package.preload['bit.numberlua']
	no file 'lua_scripts/bit\numberlua.lua'
	no file 'lua_scripts/bit\numberlua.ext'
	no file 'lua_scripts/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.moon'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.lua'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.ext'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.moon'
	no file 'lua_scripts/extensions/bit\numberlua.lua'
	no file 'lua_scripts/extensions/bit\numberlua.ext'
	no file 'lua_scripts/extensions/bit\numberlua.moon'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.lua'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.ext'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.moon'
	no file 'lua_scripts/bit\numberlua.dll'
	no file 'lua_scripts/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit\numberlua.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit\numberlua.so'
	no file 'lua_scripts/extensions/bit\numberlua.dll'
	no file 'lua_scripts/extensions/bit\numberlua.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit\numberlua.so'
	no file 'lua_scripts/bit.dll'
	no file 'lua_scripts/bit.so'
	no file 'lua_scripts/AIO_Server/bit.dll'
	no file 'lua_scripts/AIO_Server/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit.so'
	no file 'lua_scripts/extensions/bit.dll'
	no file 'lua_scripts/extensions/bit.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit.so'
module 'bit53' not found:
	
	no precompiled script '{}' found
	no field package.preload['bit53']
	no file 'lua_scripts/bit53.lua'
	no file 'lua_scripts/bit53.ext'
	no file 'lua_scripts/bit53.moon'
	no file 'lua_scripts/AIO_Server/bit53.lua'
	no file 'lua_scripts/AIO_Server/bit53.ext'
	no file 'lua_scripts/AIO_Server/bit53.moon'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.lua'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.ext'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.moon'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.lua'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.ext'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.moon'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.lua'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.ext'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.moon'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.lua'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.ext'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.moon'
	no file 'lua_scripts/extensions/bit53.lua'
	no file 'lua_scripts/extensions/bit53.ext'
	no file 'lua_scripts/extensions/bit53.moon'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.lua'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.ext'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.moon'
	no file 'lua_scripts/bit53.dll'
	no file 'lua_scripts/bit53.so'
	no file 'lua_scripts/AIO_Server/bit53.dll'
	no file 'lua_scripts/AIO_Server/bit53.so'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.dll'
	no file 'lua_scripts/AIO_Server/Dep_crc32lua/bit53.so'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.dll'
	no file 'lua_scripts/AIO_Server/Dep_LuaSrcDiet/bit53.so'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.dll'
	no file 'lua_scripts/AIO_Server/Dep_Smallfolk/bit53.so'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.dll'
	no file 'lua_scripts/AIO_Server/lualzw-zeros/bit53.so'
	no file 'lua_scripts/extensions/bit53.dll'
	no file 'lua_scripts/extensions/bit53.so'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.dll'
	no file 'lua_scripts/extensions/StackTracePlus/bit53.so'
lua_scripts/ExampleServer.lua:92: attempt to call a nil value (field 'AddOnInit')

**Comment by Rochet2** [comment]
what lua version are you using?
